### ISSUE TITLE
I can't receive data

### ISSUE THREAD

**Issue by sibche2013** [Troodi/TradingViewWebsocket#1]
Hello 
when i run your script on my host , that display this errors ... what should i do?
`PHP Notice:  Undefined property: stdClass::$user in /home/.../class.php on line 112`
`PHP Notice:  Trying to get property 'auth_token' of non-object in /home/.../123/class.php on line 112`

**Comment by Troodi** [comment]
You set correct login and password from tadingview?

**Comment by sibche2013** [comment]
> You set correct login and password from tadingview?

I have set login and password on example.php file on this function :
new Main(myusernam, mypassword);
after I run this file these errors appears :
PHP Notice:  Undefined property: stdClass::$session_id in /home/.../class.php on line 80
PHP Notice:  Undefined property: stdClass::$user in /home/.../123/class.php on line 112

**Comment by Troodi** [comment]
You execution example.php with php cli (in console)?

**Comment by sibche2013** [comment]
I run composer then open example.php by url on my linux host php : https://mysite.com/example.php

**Comment by sibche2013** [comment]
> You execution example.php with php cli (in console)?

I run composer then open example.php by url on my linux host php : https://mysite.com/example.php
i cant run cli on my host , i run composer on my localhost then transfer all files into my linux host

**Comment by Troodi** [comment]
Run this file as php cli.
php example.php on your server

**Comment by sibche2013** [comment]
> Run this file as php cli.
> php example.php on your server

yes that's work, but how can I use this by URL? i want to use this on my site with php

**Comment by Troodi** [comment]
Try after 171 line in class.php add `break;`

**Comment by sibche2013** [comment]
I've used break; there bot not happened and receive error …

**Comment by sibche2013** [comment]
> Try after 171 line in class.php add `break;`

I've used break; there bot not happened and receive error …

**Comment by Troodi** [comment]
Im updated code, you can see changes in code.

**Comment by sibche2013** [comment]
> Im updated code, you can see changes in code.

thank you problem solved@
