### ISSUE TITLE
Getting errors Token

### ISSUE THREAD

**Issue by rajkiranjeet** [Troodi/TradingViewWebsocket#2]
PHP Notice:  Undefined property: stdClass::$user in /public_html/TradingViewWebsocket/class.php on line 137
PHP Notice:  Trying to get property 'auth_token' of non-object in /public_html/TradingViewWebsocket/class.php on line 137
Hi
is it still working Script ?

**Comment by Troodi** [comment]
Hello, you set login and password? Script still working.

**Comment by C0D3M0N** [comment]
This works very beautifully worked for me.

**Comment by C0D3M0N** [comment]
> Hello, you set login and password? Script still working.

Could you explain how to change interval ? (like 1m 3m 5m ~)

**Comment by Troodi** [comment]
Yes, but i need develop this. now only real time
