### ISSUE TITLE
How could i get another interval?

### ISSUE THREAD

**Issue by C0D3M0N** [Troodi/TradingViewWebsocket#3]
I tried get another interval's data

but it's not easy to me... 
i tried chart session generate and resolve_symbol, create_series setting, but it didn't work.

anyone can do this job for me?

thanks 👍

**Comment by Troodi** [comment]
What interval do you need?

**Comment by Troodi** [comment]
I will add timeframes soon

**Comment by C0D3M0N** [comment]
> What interval do you need?

i need 1m 3m 5m ~ 1h.
I tried various settings, but in the end I didn't get the answer I was looking for.

So, I solved the problem by using another github repo based on nodejs.

**Comment by Troodi** [comment]
I have 2 repositories, specifically this one just gets the latest prices, in another repository you can get history and prices in real time
