### ISSUE TITLE
Setup quite confuse

### ISSUE THREAD

**Issue by chunhian888** [Troodi/TradingViewWebsocket#4]
Hello can i have some more details abit on how to let it works? im kinda new to programming not really sure how to make it run, already tried to apply this code on my project but couldnt run.

**Comment by Troodi** [comment]
Hello! Clone progect and run "php example.php"

**Comment by chunhian888** [comment]
clone and php example.php already but i didnt get any response return data, tried to echo something but it stopped after require 'class.php';
may ask which php version is this?
![image](https://user-images.githubusercontent.com/33050721/231628404-be38c8a4-05fd-4170-a3ad-f41bc3fd3faa.png)

**Comment by chunhian888** [comment]
it is working fine already, all i miss was some dependencies, thanks!
