### ISSUE TITLE
Installation on shared hosting

### ISSUE THREAD

**Issue by MehdiK120** [Troodi/TradingViewWebsocket#5]
Is there a way to use this script in shared hosting (cpanel)?

**Comment by Troodi** [comment]
Yes, possible run of any hosting or control panel

**Comment by MehdiK120** [comment]
The provider I bought the hosting from, doesn't allow terminal access and I can't use composer, is there another way to install the dependencies for this project?

**Comment by Troodi** [comment]
Create a php file and run the command that installs the dependencies

**Comment by MehdiK120** [comment]
Finally, I was able to run it on localhost and it works fine in CLI, but when I run the example.php file with the browser, I get a timedout error, is there a way to stop the program after receiving the first result from the tradingview?

example.php:

```
<?php

require 'class.php';

class Main {
    public function __construct()
    {
        $ws = new TradingViewWebsocket(__CLASS__);
    }

    public static function readQuotes($obj) {
        $obj->registerTicker("XAUUSD"); // Add ticker
        var_dump($obj->tickerData); // Read info from websocket
    }
}

new Main();
```

**Comment by MehdiK120** [comment]
I used `for ($i = 0; $i <= 1; $i++)` instead of `while (true)` and my problem is solved, is this method correct to limit the number of times it returns?
